language: python

python:
  - 3.4
  - 3.3
  - 2.7
  - 2.6

sudo: false

addons:
  sauce_connect: true

env:
  global:
    - secure: M+3SprdbdJKnK/Hf4EWkEY88OJaPq3ZY2v0xEdKCCq2IVrtNtSj3f3YkpYHiLWUM55AZ8Bc0m0Eizsfdyn59FQynFwzOhYsrhigWCCA7T9JbH0rZEJqNY22Z2H5F8Xm3f4qJx6eozlsHK+cguij3TJNrVPYG5y9S/+kylW1+WSA=
    - secure: HdA4aiN8py/MKwLftOBP9ji/jt3kguvol+DPGs8lZ+LcLSBB67D1sCeTzcv4IHeDEFPWMQAbEQ3V9tc9LFjpKR9w5bROw4+QHqC5zLHne/Hpu4AB1GdGSuXse/M5/GvhWiprVBz9eHnzlYmw4QGUOHR7uBZ2NYkDIe61wrm+i0o=
  matrix:
    - DJANGO=1.6 DATABASE_URL='sqlite://localhost/:memory:' SELENIUM=0
    - DJANGO=1.6 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0
    - DJANGO=1.6 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=0
    - DJANGO=1.6 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='emailuserapp.EmailUser'
    - DJANGO=1.7 DATABASE_URL='sqlite://localhost/:memory:' SELENIUM=0
    - DJANGO=1.7 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0
    - DJANGO=1.7 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=0
    - DJANGO=1.7 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='emailuserapp.EmailUser'
    - DJANGO=1.6 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='customuserapp.User'

before_script:
  - sh -c "if [ '$DATABASE_URL' = 'postgres://postgres@127.0.0.1/djangocms_test' ];
    then psql -c 'DROP DATABASE IF EXISTS djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'postgres://postgres@127.0.0.1/djangocms_test' ];
    then psql -c 'create database djangocms_test;' -U postgres; fi"
  - sh -c "if [ '$DATABASE_URL' = 'mysql://root@127.0.0.1/djangocms_test' ]; then mysql
    -e 'create database IF NOT EXISTS djangocms_test CHARACTER SET utf8 COLLATE utf8_general_ci;';
    fi"

install:
  - pip install -q -r "test_requirements/django-$DJANGO.txt"
  - if [ $DATABASE_URL == 'postgres://postgres@127.0.0.1/djangocms_test' ]; then pip
    install -q psycopg2 ; fi
  - if [ $DATABASE_URL == 'mysql://root@127.0.0.1/djangocms_test' ]; then pip install
    -q mysql-python ; fi

script: coverage run --rcfile=.coverage.rc develop.py test --migrate

after_success: coveralls --config_file=.coverage.rc --coveralls_yaml=.coveralls.yml

notifications:
  email:
    recipients:
      - digi@treepy.com
    on_success: never
    on_failure: always
  irc:
    - irc.freenode.org#django-cms
    - irc.freenode.org#django-cms-sprint

matrix:
  exclude:

    - python: 2.6
      env: DJANGO=1.7 DATABASE_URL='sqlite://localhost/:memory:' SELENIUM=0
    - python: 2.6
      env: DJANGO=1.7 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0
    - python: 2.6
      env: DJANGO=1.7 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=0
    - python: 2.6
      env: DJANGO=1.7 DATABASE_URL='postgres://postgres@127.0.0.1/djangocms_test' SELENIUM=1 AUTH_USER_MODEL='emailuserapp.EmailUser'

    - python: 3.3
      env: DJANGO=1.6 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0
    - python: 3.3
      env: DJANGO=1.7 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0

    - python: 3.4
      env: DJANGO=1.6 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0
    - python: 3.4
      env: DJANGO=1.7 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0

  allow_failures:
    - python: 2.7
      env: DJANGO=1.7 DATABASE_URL='mysql://root@127.0.0.1/djangocms_test' SELENIUM=0

  fast_finish: true
